import { useState } from 'react';

export default function DoctorSummaryModal({
  isOpen,
  onClose,
  patientName = 'Patient',
  patientAge,
  medicines = [],
  interactionWarnings = [],
  caregiverToken,
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const todayStr = new Date().toLocaleDateString('en-PK', {
    dateStyle: 'medium',
  });

  const caregiverUrl = caregiverToken ? `${window.location.origin}/caregiver/${caregiverToken}` : '';

  // Formatted text for WhatsApp and doctor clipboard
  const summaryText = `🏥 *NuskhaSaathi — Patient Medical Summary Card*
━━━━━━━━━━━━━━━━━━━━━━━━━━
👤 *Patient:* ${patientName}${patientAge ? ` (${patientAge} yrs)` : ''}
📅 *Date:* ${todayStr}

💊 *Active Prescribed Medicines (${medicines.length}):*
${medicines.length === 0 ? '• No active medicines recorded.' : medicines.map((m, i) => `${i + 1}. *${m.name}* — ${m.dosage || 'dose unspecified'}, ${m.frequency || 'timing unspecified'}${m.duration ? ` (for ${m.duration})` : ''}`).join('\n')}

${interactionWarnings.length > 0 ? `⚠️ *Identified Drug Interaction Risks:*
${interactionWarnings.map((w, i) => `${i + 1}. *${w.medicine_a} + ${w.medicine_b}:* ${w.warning_text}`).join('\n')}
` : '✅ *No Known Drug Interactions Detected*'}
${caregiverUrl ? `🔗 *Live Dosing Schedule & Prescription Link:*
${caregiverUrl}
` : ''}━━━━━━━━━━━━━━━━━━━━━━━━━━
_Generated by NuskhaSaathi · Alibaba Cloud AI Hackathon Pakistan_`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const ta = document.getElementById('doctor-summary-text');
      if (ta) {
        ta.select();
        document.execCommand('copy');
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
      }
    }
  };

  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(summaryText)}`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm">
      <div className="relative w-full max-w-lg rounded-3xl border border-teal-100 bg-white p-6 shadow-2xl transition-all sm:p-7 max-h-[90vh] flex flex-col">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute right-4 top-4 grid h-8 w-8 place-items-center rounded-full text-slate-400 hover:bg-slate-100 hover:text-slate-700"
          aria-label="Close"
        >
          ✕
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-teal-50 pb-4">
          <span className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-100 text-2xl text-teal-800">
            🏥
          </span>
          <div>
            <h3 className="text-lg font-bold text-slate-900">Doctor & ER Summary Card</h3>
            <p className="text-xs text-slate-500">
              Show or send this to any doctor or hospital to avoid dangerous medication conflicts
            </p>
          </div>
        </div>

        {/* Formatted Card Box */}
        <div className="flex-1 overflow-y-auto py-4 space-y-3">
          <div className="rounded-2xl border border-teal-200 bg-slate-50 p-4 font-mono text-xs text-slate-800 whitespace-pre-wrap leading-relaxed shadow-inner">
            {summaryText}
          </div>

          <p className="text-[11px] text-slate-500 italic">
            💡 Tip: Doctors in ER or new clinics need to know your prior medications immediately. Send this to their WhatsApp or print it.
          </p>
        </div>

        {/* Actions */}
        <div className="pt-3 border-t border-slate-100 flex flex-col sm:flex-row gap-2">
          <a
            href={whatsappUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-[#25D366] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#1EBE5D] transition"
          >
            <span>💬</span>
            <span>Send to Doctor via WhatsApp</span>
          </a>

          <button
            type="button"
            onClick={handleCopy}
            className={`inline-flex items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-bold transition ${
              copied
                ? 'bg-green-600 text-white shadow-sm'
                : 'bg-primary text-white hover:bg-primary-dark shadow-sm'
            }`}
          >
            <span>{copied ? '✓' : '📋'}</span>
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Summary'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
